### ISSUE TITLE
Incorporate new header bar design

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-web-client#83]
# Feature Request

_Use this form to outline potential new feaures or planned features in lofft_

**[Notion Link]()**

### **Feature experience**

- As a `visitor` they should be able to fill in their email into the email form. 

### **Todo**

- [ ] Add new header banner
- [ ] Move the email signup to the top of the page
- [ ] Add new art work

### **Potential Challenges**

- This should be an easy challenge for a junior to work on, most of the features already exist and just require relocating from 
the footer of the page to the top. 

## **Link to Figma board, images and design description**

_Latest design is located on the figma board_

<img width="915" alt="Screenshot 2022-08-22 at 08 22 17" src="https://user-images.githubusercontent.com/5392107/185862830-0597cba7-0cf6-43d2-b52b-b3cbcd757d91.png">
