### ISSUE TITLE
Header re-design

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-web-client#87]
# Feature Request

_Use this form to outline potential new feaures or planned features in lofft_

**[Assana Link](https://app.asana.com/0/1202685331832331/1202837989360743/f)**

### Linked Issues and PR
* [Linked Issue]()

## **Feature description**
There are some subtle redesigns on the website, as we move forward and make the website a more focal point of the application. This is a good first issue as most features are already there and just need moving around. 
### **Todo**

- [ ] Add new artwork.
- [ ] Add new header banner.
- [ ] Add e-mail signup into the header banner.
- [ ] Add German language version of the text.

### **Potential Challenges**
- Most of the features already exist and no trouble should occur during this development. 

## **Link to Figma board, images and design description**

_Latest design is located on the figma board_

**[Figma board](https://www.figma.com/file/g9mnJDgVDQRgGaWtr3qOAD/Lofft?node-id=347%3A2)**

### Screen shots
<img width="643" alt="Screenshot 2022-08-29 at 00 16 21" src="https://user-images.githubusercontent.com/5392107/187096698-cf4031fa-946f-43fb-a5ef-996a0cd74a50.png">

**Comment by Sharonusesopensource** [comment]
Hello James.
I'm excited to contribute to this project. I would be updating the features you listed above.
Regarding the new art work to be added, where do I get that from?
